trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type:       github
      ref:        main
      endpoint:   ni (2)
      name:       ni/niveristand-custom-device-build-tools
      # TEMPORARY, include fake custom device to use templates until migrating the templates into build tools makes sense
    - repository: imitation-cd
      type: github
      ref: main
      endpoint: papowerNI
      name: papowerNI/imitation-cd  
# Pipeline Completion Triggers:
  pipelines:
    - pipeline: VeristandMessageLibrary
      source:   ni.niveristand-custom-device-message-library
      trigger:  true

stages:
  - template: azure-templates/stages-template.yml@imitation-cd # TEMPORARY, Point to imitation-cd instead of build-tools
    parameters:
      lvVersionsToBuild: 
        - version: '2020'
          bitness: '32bit'
        - version: '2021'
          bitness: '64bit'
        - version: '2023'
          bitness: '64bit'

      buildSteps:
        - projectLocation: 'Source\Message Library.lvproj'
          buildOperation: 'ExecuteAllBuildSpecs'
          target: ''
          buildSpec: ''

      releaseVersion: '23.0.0'
      quarterlyReleaseVersion: '2023 Q1'
      buildOutputLocation: 'Built'
      archiveLocation: '\\daqserver\temp\papower\Measurements\VeriStandAddons\messaging_library'

      pack: true
      packages:
        - controlFileName: 'control'
          payloadMaps:
            - installLocation: 'ni-paths-LV$(lvVersion)DIR$(nipkgx64suffix)\vi.lib\NI\VeriStand Custom Device Messaging'
              payloadLocation: 'Built\VeriStand Custom Device Messaging'