[archive]
build_output_dir = 'Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\messaging_library'

[projects.library]
path = 'Source\Message Library.lvproj'

[[build.steps]]
name = 'Messaging Libraries'
type = 'lvBuildAll'
project = '{library}'

[package]
type = 'nipkg'
control_file = 'control'
payload_dir = 'Built\VeriStand Custom Device Messaging'
install_destination = 'ni-paths-LV{veristand_version}DIR{nipaths_64_bitness_suffix}\vi.lib\NI\VeriStand Custom Device Messaging'

[notification]
type = 'teams'
